### ISSUE TITLE
Feature Request: Move preset data into the runelite profiles/account

### ISSUE THREAD

**Issue by AustinGarrettR** [antero111/plugin-presets#10]
Currently the presets are saved in the presets folder in the runelite user directory.
This is not the same place as other plugins usually store their data.

The current implementation means any runelite client, with any runelite email login, or character login, all share the same presets. The presets also don't sync where you can use them on other devices.

For me, I play two characters with separate runelite sessions, where each one is logged into a separate runelite email. This allows me to have separate bank tags and plugin settings per character. When I use the preset plugin, presets are shared between clients. So if one client has its own plugin settings, and uses a preset, the next client that opens up even with a different profile will apply the plugin settings from the previously active preset from the other client, which doesn't want those settings.

The primary issue is presets are not bound to your runelite account, but are locally stored and apply to all runelite sessions.
Thanks!

**Comment by FourWolves** [comment]
Would love to see this as well

**Comment by antero111** [comment]
In the new plugin version it is possible to change the location where presets are stored with the file/cloud icon in the editor view. This toggles between the preset folder and the RuneLite configuration file (that is synced to RL accounts if logged in). 

Presets saved to the config with an account should sync to all RL session with the same account similiar to screen markers etc...

**Comment by antero111** [comment]
This is somewhat experimental feature that could be extended in the future e.g. moving completely away from the preset folder. 

Please let me know if the preset syncing works or not and if something were to be improved.
