### ISSUE TITLE
QoL Improvements to managing presets

### ISSUE THREAD

**Issue by Jademalo** [antero111/plugin-presets#20]
First of all I just wanted to say that your implementation of #4 is *excellent*. I absolutely love that you can not only enable/disable plugins individually, but also drill down into each individual setting key. This is extremely nice for things like the ground items plugin, where you might want different settings in different profiles but have a primary highlight list shared across all presets. Awesome work!

After using the new version a little bit, I've got some small quality of life suggestions to make managing things a little easier and clearer;

- When editing a preset configuration, it's not clear that clicking on the plugin name will bring up a sub menu showing each available plugin key. I would recommend moving the arrow that appears when you click on it to the left hand side of the plugin name, as well as adding a `>` arrow in front of all plugins to show they can be expanded, similar to this;
![image](https://user-images.githubusercontent.com/386846/183258870-014adfb2-fa22-49f9-9024-7e3ba3a6ffdf.png)

- It would be useful if "Enable all configurations" and "Disable all configurations" only affect the currently visible plugins as per your filter, rather than every setting. This would give a lot more flexibility in batch editing, and would be useful for setting up pairs of profiles that change the same keys.

- It would be useful to have a filter for "Only enabled" and "Only disabled" to see what a preset modifies at a glance.

- It might be worth having all keys in a new profile default to Enabled, since as it is now you have to find what you want to be saved and manually enable it. Having it default to enabled would allow you to create a profile, modify the settings you want modified, and then at a glance see what has been modified. You could then use the "Configs match" filter to show all unmodified plugins and easily disable them all, giving you a profile with just the modifications you made.
A better approach would be to make it so that when you first create a new profile, it enters a "record" mode. You then go and make the changes you want to make to your plugins, and once you're done you hit confirm. This would result in the new profile automatically saving the changes you'd just made, without you having to go and enable the plugins manually. I appreciate this might be substantially more work than the above suggestion, however.

Hopefully these suggestions aren't too difficult to implement, this plugin really is absolutely incredible!

**Comment by antero111** [comment]
Hi and thanks for the QoL improvement ideas.
Those arrows are definetly doable quite easily.

**Comment by antero111** [comment]
Hi and thanks for the QoL ideas. These improvements are definitely doable. 

Those dropdown arrows, are easy addition. Will add them to the next version.

For the enable/disable all button, it was mostly meant to be hard toggle for all plugins on/off. I'm intrested to hear how you use it to create preset pairs. For creating preset pairs, have you tried to create pairs by copying, importing and then hitting the update all modified?

For the only enabled/disabled filter option, would it basically be modified and configs match options combined and the other one for showing only those that are not in presets? If so, its easy to implement.


With v2, presets default to being "empty" since it tries to provoke using presets to only change those settings that should be changed. Having _all_ plugin configs in preset and then some few settings that really change is bad from the start since it has to loop all those configs in the preset. But as you have noted, its somewhat tedius to add configs one by one there if you. You can create presets that contain all your configs by right clicking the + icon and then edit and update all modified like you suggested there.

I like the record mode idea and it's something to be considered but realistically it would only be useful when you know in advance what you want in your preset.

**Comment by antero111** [comment]
Maybe it would look something like this.

![kuva](https://user-images.githubusercontent.com/60603897/183710871-a1fc61a0-24bc-4620-a9d5-fb98a190543a.png)

Also should presets have an option to toggle this record mode or does the current "update all modified" work? Mostly it would be only an additional layer of visual representation of that you are making changes to a some preset.

**Comment by Jademalo** [comment]
> For the enable/disable all button, it was mostly meant to be hard toggle for all plugins on/off. I'm intrested to hear how you use it to create preset pairs. 

The way I was thinking how to do it is like this;
- Start with your standard setup, and make a preset with everything enabled.
- Make a second preset, enable everything
- Modify the settings you want to change in Runelite
- In the second preset, select the "Configs match" filter, so the modified keys aren't visible
- Click "Disable all", so only the plugins that have been modified are enabled
- Click "Update all"
- Go back to your standard setup preset
- Select "Configs match"
- Click "Disable all"
Now you have a pair of plugins that modify the same keys

> For creating preset pairs, have you tried to create pairs by copying, importing and then hitting the update all modified?

No, that's a good idea too! I hadn't considered that. 

I still think there's value in having enable all/disable all only affect the plugins currently shown by the filter, though. If you don't have a filter set then it works as it does now, but it means if you have everything enabled and want to disable everything that isn't modified you can do it in one click.
It's how I would expect the function to work, I actually lost a preset when I was testing because I didn't expect it to disable *everything*, lol.

> For the only enabled/disabled filter option, would it basically be modified and configs match options combined and the other one for showing only those that are not in presets? If so, its easy to implement.

What I'm thinking is extremely simple - One filter that shows all plugins with a tick next to them, and another that shows all plugins without a tick.

> I like the record mode idea and it's something to be considered but realistically it would only be useful when you know in advance what you want in your preset.

I've found that when I make presets, I tend to make them with a specific idea in mind. For example, I wanted to make a profile for my Ironman that changed all of the GE value displays to High Alch. If I make a bunch of changes, having to remember which plugins I just changed and enable the respective plugins in the preset isn't very user friendly.
Because of this, I've been enabling every plugin when I make a new preset so that when I modify stuff, they show up as modified in the list and I can then disable everything that wasn't modified.

Record mode would solve that, since when you make your new preset and change a load of settings, those settings will get automatically enabled without you having to remember anything.

> Also should presets have an option to toggle this record mode or does the current "update all modified" work? Mostly it would be only an additional layer of visual representation of that you are making changes to a some preset.

I would say yes.
Update all modified is useful when you're changing a setting that's already tracked by the preset, but if you're changing a setting that you haven't enabled before it doesn't 


 > For the enable/disable all button, it was mostly meant to be hard toggle for all plugins on/off. I'm intrested to hear how you use it to create preset pairs. 

The way I was thinking how to do it is like this;
- Start with your standard setup, and make a preset with everything enabled.
- Make a second preset, enable everything
- Modify the settings you want to change in Runelite
- In the second preset, select the "Configs match" filter, so the modified keys aren't visible
- Click "Disable all", so only the plugins that have been modified are enabled
- Click "Update all"
- Go back to your standard setup preset
- Select "Configs match"
- Click "Disable all"
Now you have a pair of plugins that modify the same keys

> For creating preset pairs, have you tried to create pairs by copying, importing and then hitting the update all modified?

No, that's a good idea too! I hadn't considered that. 

I still think there's value in having enable all/disable all only affect the plugins currently shown by the filter, though. If you don't have a filter set then it works as it does now, but it means if you have everything enabled and want to disable everything that isn't modified you can do it in one click.
It's how I would expect the function to work, I actually lost a preset when I was testing because I didn't expect it to disable *everything*, lol.

> For the only enabled/disabled filter option, would it basically be modified and configs match options combined and the other one for showing only those that are not in presets? If so, its easy to implement.

What I'm thinking is extremely simple - One filter that shows all plugins with a tick next to them, and another that shows all plugins without a tick.

> I like the record mode idea and it's something to be considered but realistically it would only be useful when you know in advance what you want in your preset.

I've found that when I make presets, I tend to make them with a specific idea in mind. For example, I wanted to make a profile for my Ironman that changed all of the GE value displays to High Alch. If I make a bunch of changes, having to remember which plugins I just changed and enable the respective plugins in the preset isn't very user friendly.
Because of this, I've been enabling every plugin when I make a new preset so that when I modify stuff, they show up as modified in the list and I can then disable everything that wasn't modified.

Record mode would solve that, since when you make your new preset and change a load of settings, those settings will get automatically enabled without you having to remember anything.

> Also should presets have an option to toggle this record mode or does the current "update all modified" work? Mostly it would be only an additional layer of visual representation of that you are making changes to a some preset.

I would say yes.
"Update all modified" is useful when you're changing settings that are already tracked by the preset, but if you're changing a setting that you haven't enabled before it doesn't give you any sort of indication. This is where record mode is most useful, since it means you wouldn't have to try and remember which plugins you changed to enable them in the preset.


Hopefully that's clear enough, thanks again!

**Comment by antero111** [comment]
Thanks for the comprehensive answer. Many good things here to be added to the next version.

Based on this, I think that it would be good idea to edit change the toggle all funtionality to apply only to the visible plugins e.g. when filtered. 

How should the enable all work when there is modified configurations? I'd say when you click remove all, it unticks _all_ visible configurations and when enabling, it ticks all unticked configurations but does not update those configurations that are modified, those should be updated with the update all button. 

Currently the plugin updates the modified configurations with your current ones (like it would click the modified icon).

**Comment by Jademalo** [comment]
Np! :D

> How should the enable all work when there is modified configurations? I'd say when you click remove all, it unticks all visible configurations and when enabling, it ticks all unticked configurations but does not update those configurations that are modified, those should be updated with the update all button.

I agree - Enable all shouldn't update modified plugins, it should only enable currently disabled plugins.

**Comment by antero111** [comment]
Those dropdown arrows are now little better and there is now _Included_ and _Not included_ filter options that work like you described.

![java_QVoulWtFM1](https://user-images.githubusercontent.com/60603897/184410614-b7d66e9c-3edc-4704-9985-86abf87f6dd7.gif)

Also that add/remove all button works now much better.
![jRNPSdEBcz](https://user-images.githubusercontent.com/60603897/184411187-60aeecb6-dbe9-4501-9c5c-0f7cf458d0e6.gif)
 
I'll open a new issue for the record mode. Thanks for the suggestions.

**Comment by Jademalo** [comment]
Awesome work, those changes look absolutely fantastic!
