### ISSUE TITLE
A couple bugs / requests

### ISSUE THREAD

**Issue by mparsakia** [antero111/plugin-presets#26]
Hi thanks for creating this plug-in it's very useful. I wanted to share certain things I've noticed with the new version.

1. The latest UI change is confusing to navigate. The previous simple UI was a lot better to use, mostly because we could "update this preset" with an icon on the panel when we make changes to our settings + creating a new preset saved active settings upon creation.

2. It's difficult to edit the name of a preset configuration as the save/cancel buttons only flash for a second and it's too fast for me to enter text.  

3(?). If I go to 'edit a preset' and leave the panel open, within a few minutes the game begins to lag a lot. I'm not 100% sure if it's because of this plug-in, maybe there is a memory leak somewhere.

Thanks!

**Comment by Jademalo** [comment]
Regarding 1, the current functionality works in a fundamentally different way. Rather than saving *everything*, the intention is for you to only enable the modified plugins for a given preset. This means that options you change that you want changed in all of your presets will work as such, and the profiles will only affect the things you want them to.

Rather than having the preset change the settings of every plugin, it only changes the things you want the preset to change. I recommend getting used to the way it works, trust me when I say the functionality is *much* better now. 

Having said that, It's not too difficult to get the functionality you want. If you go into a preset, click the three dots, and click "Enable all configurations", all options will be stored in the profile. If you modify something as well, in the settings there will be a button showing there are modifications, and that will allow you to update everything that's changed.

**Comment by antero111** [comment]
I'll look into that performance issue and there may be something wrong with the rename.

**Comment by antero111** [comment]
> It's difficult to edit the name of a preset configuration as the save/cancel buttons only flash for a second and it's too fast for me to enter text.

Hi, I don't quite understand whats the problem here. The preset renaming works for me just fine. Could you elaborate some more on the rename problem and maybe include a gif of it not working.
Thanks.

**Comment by mparsakia** [comment]
Hey antero111, I just checked it out, maybe I updated my RuneLite recently but I don't seem to be having a problem with the renaming. Previously, it was like as if the moment I hit "Rename" it would just instantly save. I'll report back if I notice any issue again but it may have just been on my end.

**Comment by antero111** [comment]
Does the edit tab still cause lag issues or did that solve it also? Keeping the panel open does not effect the game at all to me.

**Comment by mparsakia** [comment]
I'll play some later today with the editing panel open and see if it affects anything. I wonder if there is some way I can maybe watch the RAM used while its open to profile it?

**Comment by antero111** [comment]
Can you specify your specs that you are playing rl with. Do you have some other hub plugins that might cause problems with plugin presets. Have you tried if the lag happens without plugin presets? Iirc there was some lag issues in the ToA update.

**Comment by mparsakia** [comment]
PC Specs (old, but should handle RL with 117 GPU off) i7-4770K CPU, 32GB DDR3-1600, RX580 8G GPU.

I think I see the problem now that I recorded it. The "Search Field" keeps repeatedly taking the focus of the mouse, when editing settings. So when I try to use middle mouse to pan the camera around the field keeps taking focus. I don't know why the renaming is bugged after, but my best guess is that search field when editing settings is still repeatedly requesting focus.

Link to video, currently uploading / processing:
https://streamable.com/nncd2n

As for the RL Hub plugins, I don't think I have any that would interfere with Presets, and I keep most of them off unless I am going to the specific activity. I could send a list of all my plugins/screenshots if needed.

**Comment by antero111** [comment]
Thanks for the video clip. You may be right with the field repeating focus but even if that happened, it would not cause any stuttering. I think that there has been some RL client change with past update that causes some config to be updated but I am not sure what it is. I'll have a look when I have some time.

It's still kinda weird that I don't have any performance issues with RL on the current v2.1 and in v2.2.

**Comment by mparsakia** [comment]
Oh yes let me add that information as well:
Runelite Version 1.8.32.2
Oldschool Rev 207
Launcher: 2.4.5

**Comment by antero111** [comment]
Still can't repro.
