### ISSUE TITLE
Not selected filter also show partial configs

### ISSUE THREAD

**Issue by ImFlizz** [antero111/plugin-presets#27]
When plugins are updated with configs added to them, these configs don't automatically get added to a preset, and usually we don't even know that they have been added/are new configs.

It would be really nice to have a filter for unselected configs within a preset, in the same place where the "All a to z", "modified", "configs match" etc filter is, which would show any full plugin that has not been added to the selected preset, or if some configs within a plugin have been added, it would show the configs which have not been added yet.

**Comment by antero111** [comment]
Upcoming v2.2 of the plugin has this "Included" and "Not included" filters. See this [pr](https://github.com/runelite/plugin-hub/pull/3213). Its still yet to be merged tho.

**Comment by antero111** [comment]
What do you mean with "single configs within plugins"? How should that filter work?

**Comment by ImFlizz** [comment]
I'm not sure if config is the right word to use here.
Plugins have multiple settings/configs within them that can be synced to the preset.

The not included filter currently shows only plugins where not a single one of these settings is synced. If even one of these settings is synced, the whole plugin no longer shows up within the not included filter.

It would be nice if the filter would show plugins which might have only some of their settings not included, not all.

**Comment by antero111** [comment]
Could you describe some example where you would use this kind of filter. I'm all in to improve those filters to be the best they can but I don't know if this filter is needed.

**Comment by ImFlizz** [comment]
I currently have a "default" preset which includes every setting in every plugin except a few specific ones I don't want in there. For example, the "color" options in ground markers and object markers which I might change often, as well as the nylo role selector in the tob qol plugin.

It would be nice to see which ones I haven't included incase I change my mind in the future. Also, when plugins are updated with new settings, they are not automatically added to the preset, and often I don't even know they have been added to the plugin itself.

If there is an updated filter as I outlined, it would help to find these new options I might not even know exist as well. It isn't the most important change but I think it would be great QoL.

**Comment by antero111** [comment]
Would it be any better if the "Not included" filter also showed those plugin configs that has some settings checked and also some not checked. It could also auto open the dropdowns in those partial configs.

In your case the "Not included" filter would show ground markers since you have some unticked configs there.

![kuva](https://user-images.githubusercontent.com/60603897/188326015-9f261814-d10f-4e97-b678-1e8f4c095725.png)

**Comment by ImFlizz** [comment]
Yes, that is exactly what I wanted.

**Comment by antero111** [comment]
![l1vzNVrYON](https://user-images.githubusercontent.com/60603897/194539396-64a576f1-a2d9-47de-8449-5914e57323ff.gif)

Hi, added this feature in https://github.com/antero111/plugin-presets/commit/70404f0418de04a975650053edf0784ff599e7bb.

Also added "Open all", "Open partial" and "Close all" buttons.
