### ISSUE TITLE
"Modified" doesn't appear when creating a new profile

### ISSUE THREAD

**Issue by Jademalo** [antero111/plugin-presets#28]
If I make a new profile and select a key in the config, then click the settings tab and modify that key, when I go back to the plugin presets tab "Modified" doesn't appear next to that key.
I have to exit out of the preset to the top menu, then go back in to the presets config in order for "Modified" to be there.

This only happens when creating a new preset. If you have an existing preset, go into the config, then click the settings tab to modify the key, when you go back to the preset tab "Modified" will be there.

**Comment by antero111** [comment]
I am not able to reproduce that modified text problem. Works correctly for me.
Which configuration did you modify that did not show as modified?

**Comment by Jademalo** [comment]
Ah, after a bit more testing it seems to be related to custom keys.

https://youtu.be/L9nTzs4wmlo
Here's a quick video showing it.

**Comment by antero111** [comment]
Thanks for the video. This is due to bad logic with how those custom settings are handled. I'll fix

**Comment by antero111** [comment]
See this https://github.com/antero111/plugin-presets/issues/34 for a new issue about fixing this. There is something wrong with custom settings that they don't work as reliably as they should.
