### ISSUE TITLE
Clear hotkey button

### ISSUE THREAD

**Issue by BladeBTW** [antero111/plugin-presets#31]
Hello!

Big fan of this plugin!

To clear any hotkey set to profiles I now have to go to the presets folder and manually edit the .json file.
I would really love a button that clears the set hot key for a plugin preset. (Or a way to right click reset hotkey).

**Comment by antero111** [comment]
You can clear the keybind by hitting backspace and clicking save. Maybe there should be a button for this.

**Comment by BladeBTW** [comment]
Thank you so much !!
