### ISSUE TITLE
Preset activation based on window focus

### ISSUE THREAD

**Issue by BladeBTW** [antero111/plugin-presets#33]
An amazing feature would be the option to trigger a plugin preset on window activation or deactivation (basically if the client is focused or not), or both.
Useful thing about this is that if you are playing other games while playing osrs, or playing multiple accounts you are able to for example limit your rendering distance when unfocused.
This will help with preserving computing power (combined with the already existing unfocused FPS limiting option in the FPS plugin).

You can also make RL send you extra notifications when unfocused for example (by tweaking idle notifier when unfocused).

**Comment by antero111** [comment]
This is very interesting feature. Might look if this is possible.

One thing is that it must be used relatively lightly since when changing (big) presets it lags out a little, since rl loads those new settings and when alt tabbing or changing between rs clients, many preset loads happen back to back so it will get laggy. 

_But_ when chaning only handfull of configs e.g. FPS limit or draw distance, it could work quite well.

Presets could have some toggle button to "load when unfocused" and "load when focused".

**Comment by BladeBTW** [comment]
Yeah I've noticed the lagg; but for changing one or maybe up to 10 settings it will work fine on most devices I expect. Glad you like the idea; I've said it before but your plugin changes the way I play the game quite a lot. So thank you for getting it into RuneLite. <3

**Comment by BladeBTW** [comment]
One way it could be used is change the size of your client. Make the client small if it's inactive & larger if active.

**Comment by BladeBTW** [comment]
Most people including myself don't like using AHK, especially when logged in haha.
I use AHK to boot up all my accounts. AHK could do this, but I would highly prefer a RL native way of doing it of course. And I think others would too! :P

**Comment by antero111** [comment]
![NVIDIA_Share_FplrdOqsdJ](https://user-images.githubusercontent.com/60603897/194123492-5e3cca55-3ccc-465c-bae8-9f5374b11522.gif)

This must be used with care since it will lag quite easily but I think for fps limitting or skybox color and such, it will work fine.

**Comment by BladeBTW** [comment]
Yeah I think it depends on the plugin as well right? certain plugins will be heavier to load than others.
This is amazing by the way!

**Comment by antero111** [comment]
Yeah it does.

**Comment by antero111** [comment]
There needs to be some indicator that some preset will get loaded when client gets focused or unfocuses.
How would you like to have that information shown? I'm open to all ideas.

**Comment by BladeBTW** [comment]
> There needs to be some indicator that some preset will get loaded when client gets focused or unfocuses. How would you like to have that information shown? I'm open to all ideas.

Thanks for even considering me :)

**Comment by antero111** [comment]
That diagonal screen icon is very good idea. I have been trying some ideas myself but that is pretty much the best one so far. I guess its somewhat similiar to the Screen Marker plugins sidebar icon. 

Currently I have it so that you right click the load preset icon to open a context menu where you can set your desired focus action.

![kuva](https://user-images.githubusercontent.com/60603897/194615475-dfeb9a1c-9bee-4caf-9420-98f0c39bc243.png)

**Comment by BladeBTW** [comment]
Nice you got that working! Didn't know that was possible.
Yeah the screen marker icon would work. With the dominant color indicating the focus.

Maybe a combination of the icon and menu option you got there would be best.
With a visual indicator but you can trigger it by rightclicking, or by toggling the icons.

**Comment by antero111** [comment]
![wl2UhObIEx](https://user-images.githubusercontent.com/60603897/194621418-6e03f2a3-1911-492b-8698-25d80ffb3c13.gif)

How do these look?

**Comment by BladeBTW** [comment]
I like how it works!!
The icons are nice.
I'd make the corners round to match the icon on the left and if possible give it the same height?

**Comment by antero111** [comment]
I'd say square corners to look more like RL client (kinda far fetched).
That icon is same size as the ones on the right side but I guess this one could be little smaller.

**Comment by BladeBTW** [comment]
> I'd say square corners to look more like RL client (kinda far fetched). That icon is same size as the ones on the right side but I guess this one could be little smaller.

You could also say they are more recognizable as monitor screens with the hard corners.
The reason I say same px height is because I see the row snap in height.

Anyways it's cherry picking, that functionality looks amazing.

**Comment by antero111** [comment]
Added here https://github.com/antero111/plugin-presets/commit/868367b82c18126590930c1cb16fc24dee77f025.
It will be available in the next plugin update.
