### ISSUE TITLE
Opening a second client  makes presets dissapear

### ISSUE THREAD

**Issue by jevonsp** [antero111/plugin-presets#37]
Dunno if this is easily fixable, but the main reason i like your plugin is for mulitlogging and quickly getting settings how i like them

is it possible to fix this behavior? I would really like to be able to change presets even after opening a second client window. 🙏

**Comment by antero111** [comment]
Hi jevonsp and thanks for the issue. Can you describe your described behaviour little more with these questions?

Are those presets that disappear saved to config?
Are you able to reproduce this behaviour and how exactly? 
Are you logged in to RuneLite with Google account?
What os are you playing?

Iirc when opening another client the presets should not disappear...

**Comment by jevonsp** [comment]
Sorry I suppose I wasn't specific. 

When you say saved to config do you mean the preset folder? It appears they are gone from the folder.

I can reproduce this behavior by opening another client, any existing presets disappear. upon closing and reopening one client, the preset are back. 

yeah i'm signed into runelite

i'm playing on win 10 

happy to help with any more info needed

**Comment by antero111** [comment]
Saved on config means that they are saved to the settings.properties RuneLite configuration file. Do the disappearing presets have the cloud icon visible?

Do those presets get deleted or are they just not visible on the other client? 

Try to right-click the green + icon and select 'refresh presets' and see if that makes any changes on the other client.

**Comment by antero111** [comment]
Haven't been able to reproduce this.

**Comment by antero111** [comment]
@Godric777-OpenRSC Are those disappearing presets saved to config (cloud icon)? Does _refresh presets_ under the green + help?

Have you made some changes to default RL settings e.g. logged in with google, playing with Jagex launcher or done something like this https://github.com/runelite/runelite/wiki/General-Features#playing-with-multiple-accounts ?

I tested with clean install of RL and it works with me. I guess that some of those multi-account features and presets saved to config are the issue. I don't use those so might have missed them.

**Comment by antero111** [comment]
Can't reproduce. Reopen if still relevant
