### ISSUE TITLE
Importing configuration

### ISSUE THREAD

**Issue by brainard52** [antero111/plugin-presets#38]
I find manually configuring all of the different presets to be somewhat tedious. It would be nice to be able to import the general configuration as a preset so that I can use that as a base.

**Comment by antero111** [comment]
Can you elaborate more on the "import general configurartion as preset.

It's true that making multiple presets is kinda tedious but making use of copy/import and filters makes it work.

How would you improve the preset making and editing experience?

**Comment by antero111** [comment]
Elaborate more. Reopen if still relevant
