### ISSUE TITLE
Custom keys enhancements

### ISSUE THREAD

**Issue by equirs** [antero111/plugin-presets#39]
I've been working on some presets intended for sharing and have been using custom settings keys for ground markers in certain regions so that they can be added / removed depending on the preset. I know custom keys are a bit more experimental, but I have been having difficulty setting this up. Had a few ideas that would make this easier for me and others who want to edit these presets:

* This one is more of a question, but why would anyone need to enter the `configName` when inputting the custom key? Couldn't you use the config name for the plugin you've chosen to add a custom key to? Or at least use it as the default whenever there's no `.` in the input.
* Entering a custom key requires right clicking the plugin in the preset list twice, since the right click is what adds the `JPopupMenu`. This menu should be added immediately onto the `JLabel` so that the first right click opens the menu.
* I'd like to see the custom settings key that I just added in the dropdown for the plugin of the preset I'm editing, ~~maybe with an "x" button instead of a checkbox to remove that custom key from the preset~~ (moved to #42). Looking at the code, I'm not sure why these aren't displayed in the dropdown already... it's present in the preset when copied to the clipboard, but it's not there when running `plugin.getCurrentConfigurations()` when opening the edit panel. There's something going on here that I don't understand.
* This might be difficult, but similar to how changes in non-custom config values prompt for updating the preset, I'd love to see that happen when a custom key changes its value.

I'm willing to help contribute here and can get a PR up when I get the chance, if that's alright with you.

**Comment by antero111** [comment]
Hi, thanks for the comment. PR:s are more than welcome! Here is some answers to your questions: 

> This one is more of a question, but why would anyone need to enter the configName when inputting the custom key? Couldn't you use the config name for the plugin you've chosen to add a custom key to? Or at least use it as the default whenever there's no . in the input.

Some settings (mostly those used as custom settings) that you can't edit from the configurations tab have different config names that get passed to ConfigManager.setConfiguration(). For example with screenmarkers, the plugins configname is _screenmarkersplugin_ but the setting that stores the markers itself has _screenmarkers_ config name.

 Plugin presets looks at PluginManager.getPlugins() and gets every plugins config name from there and then fetches the settings to that plugin with getConfigurations. Some settings are not available with the default configName we get "automatically" from the getPlugins, so then you would have to manually add new configName (and key) such as screenmarkers.markers

It could be simplified but I just made it like that because the simplest way to add some setting is to just copy the whole setting row from the settings.properties file and paste that to the input box.

> Entering a custom key requires right clicking the plugin in the preset list twice, since the right click is what adds the JPopupMenu. This menu should be added immediately onto the JLabel so that the first right click opens the menu.'

This fixes it.

> I'd like to see the custom settings key that I just added in the dropdown for the plugin of the preset I'm editing, maybe with an "x" button instead of a checkbox to remove that custom key from the preset. Looking at the code, I'm not sure why these aren't displayed in the dropdown already... it's present in the preset when copied to the clipboard, but it's not there when running plugin.getCurrentConfigurations() when opening the edit panel. There's something going on here that I don't understand.

This might be broken somehow because previously it did show. The x button is a good idea.

> This might be difficult, but similar to how changes in non-custom config values prompt for updating the preset, I'd love to see that happen when a custom key changes its value.

They should show modified like to non-customs do. I'll have a look at this if something has changed in the client during the past month.

**Comment by equirs** [comment]
> It could be simplified but I just made it like that because the simplest way to add some setting is to just copy the whole setting row from the settings.properties file and paste that to the input box.

I see, and that makes more sense now. I was looking for my keys in the source code.

On custom settings not working as intended, I've been digging around trying to find why that is, and what I'm noticing now is that there are different instances of `CustomSettings` that are referenced when populating the current configs from `PluginPresetsCurrentConfigManager` vs parsing the preset custom settings from `PluginPresetsPlugin`. I'm thinking some of these manager classes should be `@Singleton` so that they share one instance whenever they're injected. Changing this fixes the issue on my end.

I'll put a PR up once I clean up my code a little. Thanks for your help.

**Comment by antero111** [comment]
> I'd like to see the custom settings key that I just added in the dropdown for the plugin of the preset I'm editing, maybe with an "x" button instead of a checkbox to remove that custom key from the preset.

The checkbox works but should be changed to X remove button. See https://github.com/antero111/plugin-presets/issues/42.

What do you think, should we update the plugin to v2.3.2 straight away with your fixes or wait and include some of those other issues? I'm open to just updating this as soon as the pr gets merged.

**Comment by equirs** [comment]
> > I'd like to see the custom settings key that I just added in the dropdown for the plugin of the preset I'm editing, maybe with an "x" button instead of a checkbox to remove that custom key from the preset.
> 
> The checkbox works but should be changed to X remove button. See #42.
> 
> What do you think, should we update the plugin to v2.3.2 straight away with your fixes or wait and include some of those other issues? I'm open to just updating this as soon as the pr gets merged.

I think it makes sense as a separate issue that can be fixed at a later time, since the custom settings not displaying was the main issue, at least for me.
