### ISSUE TITLE
Way to include only enabled plugins

### ISSUE THREAD

**Issue by AardPlugs** [antero111/plugin-presets#47]
Am not sure where you would like me to post the Suggestion, so here it goes

I think it would be a good thing with a way to Export, Current Plugin List
So when you trying to make your first Setup it wont take that long. because you can then just copy to clipboard After that

**Comment by antero111** [comment]
I am not sure what you are wanting here. If you want to create a preset containing all of your plugin settings e.g. a base preset, you can right click the green + icon and choose "Create new preset with all settings"

**Comment by AardPlugs** [comment]
What i mean is, i wanna be able to make a Setup that Mimics my Current Active plugins. 
Not all of them, and not None of them, but all the current Active

**Comment by antero111** [comment]
You would like a way for having presets contain only those plugins that are enabled in the settings tab?

**Comment by AardPlugs** [comment]
Well to me it would just be a easier way to create Setups, because then i can just use my "base" Setup without any unnecery Plugins, in that way i can make each setup use "Base" plugins + Neccery Plugins for given Action i dedicate the setup for, if you know what i mean

**Comment by antero111** [comment]
I guess it could work. I'd still suggest that you should keep your base plugins out of every preset and only change those that really need changing.

I'd like to hear about what kind of activities do you use presets that include base plugins and plugins for given action. I have really never tought about having presets that only include those plugins that you have enabled.

**Comment by antero111** [comment]
Hi, added Plugin enabled/disabled filter options in https://github.com/antero111/plugin-presets/commit/6d10518a1819cde0a1ec5b63a86af0b5632f9df2.

You can now create presets that only contain configs of plugins that are enabled by choosing the "Plugin disabled" filter and then clicking the ellipsis button and choosing "remove all".
