### ISSUE TITLE
Screenmarkers

### ISSUE THREAD

**Issue by pidbullz** [antero111/plugin-presets#48]
Hi, I'm trying to make screenmarkers work, however your explanation is too technical and vague. Could you explain it more clear? Like, how I read it now I don't know where to put what and when.. 
I've somehow managed to add a preset that will show up one of my markers, but im trying to see how I can toggle it off aswell as have multiple like in your gif.. I don't know how to do that even with your explanation.

Thank you in advance

**Comment by antero111** [comment]
I made some additions to that wiki page. I'd suggest that you try this way https://github.com/antero111/plugin-presets/wiki/Screen-Markers#easy-way about only changing the visibility of screen markers with presets.

Thanks for the comment.
