### ISSUE TITLE
Multilogging/Multi-activity QoL (Hotkeys/RSN-bound presets)

### ISSUE THREAD

**Issue by ArtsicleOfficial** [antero111/plugin-presets#5]
It would cut down a lot of time if we could use hotkeys to select certain presets, especially with multiple clients. As of right now, it takes me approximately twenty seconds to select a preset across 4 clients including opening the panel, selecting the preset, and closing the panel.  

Having simple hotkeys such as "Alt+1" for the first preset and "Alt+2" for the second would suffice and I imagine would be easier to implement than custom hotkeys.

I'd like to be able to very quickly focus each client and press a key and get all my presets selected across four clients done in under four seconds ideally, and I think this is the solution.

...

Another proposed idea is to allow the user to configure a list of RSNs to each preset, such as listing all alts to an alting preset, and a main to a main preset.

**Comment by antero111** [comment]
In what cirmuctances you see yourself quickly switching presets? Is it when you log in to different accounts and use different presets on each one?

**Comment by ArtsicleOfficial** [comment]
> In what cirmuctances you see yourself quickly switching presets? Is it when you log in to different accounts and use different presets on each one?

When I'm switching activities on multiple accounts, such as going from quadrolo bandos to vyre-alting on four accounts, I'd like to be able to quickly switch each account.

However, for just logging in, it would be nice to have an automatic preset applied per the account upon log-in. For when the default preset here is not the required one, hotkeys would come in usefully.

**Comment by antero111** [comment]
Will look into this after holidays.

**Comment by antero111** [comment]
Keybinds will be implemented in v2.0. Have to rethink about the rsn preset loading if its viable.
Really no eta yet.

**Comment by antero111** [comment]
In the new plugin version it is possible to bind presets to keybinds. 

[Keybind demo](https://github.com/antero111/plugin-presets/blob/master/readme_visuals/keybind_demo.gif)

See the new readme for a how to.

Rsn bound presets is now somewhat possible if you have a RuneLite account for each rsn and then save rsn presets to the RuneLite conifguration file that is synced to the RL account. You can change the location where presets are stored with the file/cloud button in the edit panel.
