### ISSUE TITLE
Missing update / sync button?

### ISSUE THREAD

**Issue by Nick2bad4u** [antero111/plugin-presets#50]
![83b38766ffffd6aa0a4448ce7a92362d 1](https://user-images.githubusercontent.com/20943337/213898150-02e4f7f6-97a6-40c3-b6a2-d87c2f78c431.png)

Any Idea why?

**Comment by antero111** [comment]
If you mean the toggle switch is not showing, edit the preset and add some configs to it and then it will be shown.

**Comment by Nick2bad4u** [comment]
> If you mean the toggle switch is not showing, edit the preset and add some configs to it and then it will be shown.

Sorry I was not clear, the sync button from inside the settings. I took wrong screenshot.

Arent I supposed to be able to sync all my current plugins configs to a profile? 
![5dbcbdbf839bdc87c7782e609d728f25 1](https://user-images.githubusercontent.com/20943337/213929155-490f3779-36d4-4ef0-8d6b-d37a3240be1f.png)

**Comment by antero111** [comment]
This button shows when you have some configurations modified.

![kuva](https://user-images.githubusercontent.com/60603897/213935426-a03f320a-50ca-4a43-a999-8ca7d4d9e86b.png)

If you wan't to include all of your settings (or sync your settings if I understand you correctly) to a certain preset, choose "create preset with all settings" or in the edit mode click the ellipsis button and choose "Add all"

![kuva](https://user-images.githubusercontent.com/60603897/213935506-f3463f74-0c6a-446f-921a-bf2a31ca2bbc.png)

![kuva](https://user-images.githubusercontent.com/60603897/213935603-e0dd955a-1953-4a12-858d-3bdc1877c8f4.png)

**Comment by antero111** [comment]
Reopen if still a problem.
