### ISSUE TITLE
Is there a way to import the configuration you already have?

### ISSUE THREAD

**Issue by OilyHands** [antero111/plugin-presets#57]
I have so many plugins I have trouble keeping track of what they do. I am beginning to use the plugin, and for my 'default' setup I would like to just import everything I already have active (ideally with their configurations too...?). The alternative, is clicking individual boxes to reach my default setup.

Very cool plugin! Thanks.

**Comment by antero111** [comment]
To add all of your configurations to a preset you can create a new preset with all settings 

![kuva](https://user-images.githubusercontent.com/60603897/219900530-5e82d474-a5c4-4585-a87e-43f856850723.png)

or in the edit panel select "Add all" from the ellipsis menu

![kuva](https://user-images.githubusercontent.com/60603897/219900537-c6243571-b87a-4da9-bc86-97d6040e1397.png)
