### ISSUE TITLE
"current configuration is same as preset setup"

### ISSUE THREAD

**Issue by BASEDNWAH** [antero111/plugin-presets#59]
I can't get this to work at all. I am playing without the HD plugin turned on. I create a preset that is only containing the HD plugin. I try to toggle it on/off and it gives that message. In fact it says it is already toggled on (the bar shows orange) but my HD plugin is not turned on. 

Is this a known issue?

**Comment by antero111** [comment]
Presets only store one state of a plugin like you have stored the HD plugins _off_ state to your preset. Nothing seems to be wrong in the plugin and it seems that you are just missing the other toggling preset pair to your HD plugin preset.

Presets don't have the ability to be toggled off. That is implemented by having a pair of preset where the other toggles the plugin on and the other turns it off.

See the [Plugin toggler preset](https://github.com/antero111/plugin-presets/wiki/Plugin-toggler-presets) example on the wiki.  Follow that example to make toggle presets for your HD plugin.

**Comment by BASEDNWAH** [comment]
> Presets only store one state of a plugin like you have stored the HD plugins _off_ state to your preset. Nothing seems to be wrong in the plugin and it seems that you are just missing the other toggling preset pair to your HD plugin preset.
> 
> Presets don't have the ability to be toggled off. That is implemented by having a pair of preset where the other toggles the plugin on and the other turns it off.
> 
> See the [Plugin toggler preset](https://github.com/antero111/plugin-presets/wiki/Plugin-toggler-presets) example on the wiki. Follow that example to make toggle presets for your HD plugin.

Hey thanks a lot you were right I misunderstood how the presets worked. I can now turn my HD plugin on and off with hotkey this is great :)
