### ISSUE TITLE
disabling presets

### ISSUE THREAD

**Issue by Eoin1248** [antero111/plugin-presets#66]
When trying to disable a preset nothing happens, it stays enabled. Using keybinds makes no difference. 
![disable](https://github.com/antero111/plugin-presets/assets/71835205/2405463c-ce75-4ee6-beec-92e77344d157)

**Comment by CloudyMischief** [comment]
I am experiencing the same issue

**Comment by antero111** [comment]
Such feature is not currently supported. We exprimented with preset disabling but did not have any sufficient conclusion about the wanted behaviour. 

Please see our discussion here https://github.com/antero111/plugin-presets/issues/54.

For current plugin usage see this section of the wiki https://github.com/antero111/plugin-presets/wiki/General-Features#using-plugin-presets.

The point is to have 2 presets that store different plugin setting states and then you are able to switch between them. If you wan't to have an agility preset that e.g. turn agility plugin on, you make that preset and you make a "counter preset" for that e.g. some "Base" preset that stores your base plugin settings (where the agility plugin is off). 

Please contribute to the said issues discussion about the preset disabling. I'm ready to implement it once we have an idea of how it should work.
