### ISSUE TITLE
Add Prayer order + filter to configurable presets

### ISSUE THREAD

**Issue by Snakethumbs** [antero111/plugin-presets#70]
Adding prayer reordering and filtering to configurable presets would be extremely useful for certain account types and activities, I personally would use it for switching between main/pure/zerk mode in LMS, would also be nice in general to switch between a PKing and PvMing loadout in general!

**Comment by antero111** [comment]
Hi, actually prayer order presets are possible with a little help of custom settings and some manual configuration. I created a guide for you to the [plugin wiki](https://github.com/antero111/plugin-presets/wiki/Prayer-order-presets). 

I hope that you can get them working, it might take some configuration but once you get the spellbook added to the preset, creating more copies is no big deal.
