### ISSUE TITLE
Mouse binds for keypress toggles?

### ISSUE THREAD

**Issue by devqhp** [antero111/plugin-presets#75]
Is it possible to use mouse events to toggle presets? For example, I would like to bind Mouse 4 and Mouse 5 to different presets to change between them quickly. Thanks for a great plugin!

**Comment by antero111** [comment]
You can't bind mouse buttons to keybinds and such system most likely won't be added due its nature of implementation. But you can achieve such system by binding your mouse button to some certain key that then can be bound to preset. Most gaming mice have such system and also you can do it easily with AHK ... just keep it 1:1.
